name 'arsellamotd-motd'
version '0.1.0'
source 'git://github.com/arsellamotd/puppet-module-motd.git'
author 'arsellamotd'
license 'Apache 2.0'
summary 'put a summary here'
description 'put a description here'
project_page 'https://github.com/arsellamotd/puppet-module-motd'

dependency 'puppetlabs/stdlib', '>= 4.6.0'
